version: "3"

services:
  nginx:
    build:
      args:
        CONFIG_PATH: /etc/nginx/sites-available/dd-dev.conf
    ports:
      - "8080:80"
  mongo:
    ports:
      - "27017:27017"
  backend:
    command: ["npm", "run", "start:dev"]
    volumes:
      - ./dd-nest:/usr/src/app
      - /usr/src/app/node_modules/
    environment:
      - BASE_URL=http://darlingdove.test:8080
      - YANDEX_WALLET=test_yandex_wallet
      - YANDEX_PAYMENT_NOTIFICATION_SECRET=test_yandex_notification_secret
      - JWT_SECRET=jwt_secret
  frontend:
    command: ["npm", "run", "start:dev"]
    volumes:
      - ./dd-front:/usr/src/app
      - /usr/src/app/node_modules/
    environment:
      - CLIENT_BASE_URL=http://darlingdove.test:8080
