version: "3"

services:
  nginx:
    depends_on:
      - backend
      - frontend
    build:
      context: ./nginx
    volumes:
      - static:/var/www/static
  mongo:
    image: mongo:4
    volumes:
      - dbdata:/data/db
  backend:
    depends_on:
      - mongo
    build:
      context: ./dd-nest
    volumes:
      - static:/var/www/static
    environment:
      - PORT=8000
      - STATIC_DIR=/var/www/static
      - MONGO_CONNECTION=mongodb://mongo/dd
  frontend:
    depends_on:
      - backend
    build:
      context: ./dd-front
    environment:
      - PORT=3000
      - SERVER_BASE_URL=http://backend:8000/api

volumes:
  dbdata:
  static:
