version: "3"

services:
  nginx:
    ports:
      - "8080:80"
  mongo:
    ports:
      - "27017:27017"
  backend:
    command: ["npm", "run", "start:dev"]
    volumes:
      - ./dd-nest:/usr/src/app
      - /usr/src/app/node_modules/
  frontend:
    command: ["npm", "run", "start:dev"]
    volumes:
      - ./dd-front:/usr/src/app
      - /usr/src/app/node_modules/
    environment:
      - CLIENT_BASE_URL=http://darlingdove.test:8080/api
